org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
kotlin.code.style=official
android.useAndroidX=true
android.debug.obsoleteApi=true
android.nonTransitiveRClass=true
# local workaround: Kotlin incremental cache corruption on this machine (2026-08-19)
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
